// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.sdust.vcard_manager;

import edu.sdust.vcard_manager.Card;
import edu.sdust.vcard_manager.CardDataOnDemand;
import edu.sdust.vcard_manager.CardIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CardIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CardIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CardIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CardIntegrationTest: @Transactional;
    
    @Autowired
    CardDataOnDemand CardIntegrationTest.dod;
    
    @Test
    public void CardIntegrationTest.testCountCards() {
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        long count = Card.countCards();
        Assert.assertTrue("Counter for 'Card' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CardIntegrationTest.testFindCard() {
        Card obj = dod.getRandomCard();
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = Card.findCard(id);
        Assert.assertNotNull("Find method for 'Card' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Card' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CardIntegrationTest.testFindAllCards() {
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        long count = Card.countCards();
        Assert.assertTrue("Too expensive to perform a find all test for 'Card', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Card> result = Card.findAllCards();
        Assert.assertNotNull("Find all method for 'Card' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Card' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CardIntegrationTest.testFindCardEntries() {
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        long count = Card.countCards();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Card> result = Card.findCardEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Card' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Card' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CardIntegrationTest.testFlush() {
        Card obj = dod.getRandomCard();
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = Card.findCard(id);
        Assert.assertNotNull("Find method for 'Card' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCard(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Card' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CardIntegrationTest.testMergeUpdate() {
        Card obj = dod.getRandomCard();
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = Card.findCard(id);
        boolean modified =  dod.modifyCard(obj);
        Integer currentVersion = obj.getVersion();
        Card merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Card' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CardIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", dod.getRandomCard());
        Card obj = dod.getNewTransientCard(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Card' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Card' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Card' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CardIntegrationTest.testRemove() {
        Card obj = dod.getRandomCard();
        Assert.assertNotNull("Data on demand for 'Card' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Card' failed to provide an identifier", id);
        obj = Card.findCard(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Card' with identifier '" + id + "'", Card.findCard(id));
    }
    
}
