// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.sdust.vcard_manager;

import edu.sdust.vcard_manager.Card;
import edu.sdust.vcard_manager.CardDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect CardDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CardDataOnDemand: @Component;
    
    private Random CardDataOnDemand.rnd = new SecureRandom();
    
    private List<Card> CardDataOnDemand.data;
    
    public Card CardDataOnDemand.getNewTransientCard(int index) {
        Card obj = new Card();
        setCreatedAt(obj, index);
        setDeleted(obj, index);
        setImgBack(obj, index);
        setImgFront(obj, index);
        setIsMe(obj, index);
        setUpdatedAt(obj, index);
        return obj;
    }
    
    public void CardDataOnDemand.setCreatedAt(Card obj, int index) {
        Date createdAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedAt(createdAt);
    }
    
    public void CardDataOnDemand.setDeleted(Card obj, int index) {
        Boolean deleted = Boolean.TRUE;
        obj.setDeleted(deleted);
    }
    
    public void CardDataOnDemand.setImgBack(Card obj, int index) {
        byte[] imgBack = String.valueOf(index).getBytes();
        obj.setImgBack(imgBack);
    }
    
    public void CardDataOnDemand.setImgFront(Card obj, int index) {
        byte[] imgFront = String.valueOf(index).getBytes();
        obj.setImgFront(imgFront);
    }
    
    public void CardDataOnDemand.setIsMe(Card obj, int index) {
        Boolean isMe = Boolean.TRUE;
        obj.setIsMe(isMe);
    }
    
    public void CardDataOnDemand.setUpdatedAt(Card obj, int index) {
        Date updatedAt = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedAt(updatedAt);
    }
    
    public Card CardDataOnDemand.getSpecificCard(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Card obj = data.get(index);
        Long id = obj.getId();
        return Card.findCard(id);
    }
    
    public Card CardDataOnDemand.getRandomCard() {
        init();
        Card obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Card.findCard(id);
    }
    
    public boolean CardDataOnDemand.modifyCard(Card obj) {
        return false;
    }
    
    public void CardDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Card.findCardEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Card' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Card>();
        for (int i = 0; i < 10; i++) {
            Card obj = getNewTransientCard(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
