// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.sdust.vcard_manager;

import edu.sdust.vcard_manager.InfoIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect InfoIntegrationTest_Roo_Configurable {
    
    declare @type: InfoIntegrationTest: @Configurable;
    
}
