// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package edu.sdust.vcard_manager;

import edu.sdust.vcard_manager.Info;
import edu.sdust.vcard_manager.InfoDataOnDemand;
import edu.sdust.vcard_manager.InfoIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect InfoIntegrationTest_Roo_IntegrationTest {
    
    declare @type: InfoIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: InfoIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: InfoIntegrationTest: @Transactional;
    
    @Autowired
    InfoDataOnDemand InfoIntegrationTest.dod;
    
    @Test
    public void InfoIntegrationTest.testCountInfoes() {
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", dod.getRandomInfo());
        long count = Info.countInfoes();
        Assert.assertTrue("Counter for 'Info' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void InfoIntegrationTest.testFindInfo() {
        Info obj = dod.getRandomInfo();
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Info' failed to provide an identifier", id);
        obj = Info.findInfo(id);
        Assert.assertNotNull("Find method for 'Info' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Info' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void InfoIntegrationTest.testFindAllInfoes() {
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", dod.getRandomInfo());
        long count = Info.countInfoes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Info', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Info> result = Info.findAllInfoes();
        Assert.assertNotNull("Find all method for 'Info' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Info' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void InfoIntegrationTest.testFindInfoEntries() {
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", dod.getRandomInfo());
        long count = Info.countInfoes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Info> result = Info.findInfoEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Info' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Info' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void InfoIntegrationTest.testFlush() {
        Info obj = dod.getRandomInfo();
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Info' failed to provide an identifier", id);
        obj = Info.findInfo(id);
        Assert.assertNotNull("Find method for 'Info' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyInfo(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Info' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InfoIntegrationTest.testMergeUpdate() {
        Info obj = dod.getRandomInfo();
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Info' failed to provide an identifier", id);
        obj = Info.findInfo(id);
        boolean modified =  dod.modifyInfo(obj);
        Integer currentVersion = obj.getVersion();
        Info merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Info' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void InfoIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", dod.getRandomInfo());
        Info obj = dod.getNewTransientInfo(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Info' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Info' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Info' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void InfoIntegrationTest.testRemove() {
        Info obj = dod.getRandomInfo();
        Assert.assertNotNull("Data on demand for 'Info' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Info' failed to provide an identifier", id);
        obj = Info.findInfo(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Info' with identifier '" + id + "'", Info.findInfo(id));
    }
    
}
